name: Build and Deploy Docs

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "*"

jobs:

  check-flake:
    runs-on: ci-ocf-mkdocs
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@v9

  build_and_deploy:

    runs-on: ci-ocf-mkdocs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Nix
        run: nix build

      - name: Setup SSH keys
        run: |
          echo '${{ secrets.BESTDOCS_DEPLOY_PRIVKEY }}' > id_ed25519
          chmod 400 id_ed25519
          echo "amethyst.ocf.berkeley.edu ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIlmVSSUC4PTOzfMvsHbUVr1e+7GLXvIPx1tX+W3CIU1" > known_hosts
          chmod 400 known_hosts

      - name: Deploy with rsync
        run: nix develop .#deploy -c rsync -e "ssh -o UserKnownHostsFile=known_hosts -i id_ed25519" --verbose --compress --partial --checksum --progress --human-readable --archive --delete result/ deploy-bestdocs@amethyst.ocf.berkeley.edu:/var/www/bestdocs

